apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: core-serve-project
  source:
    repoURL: https://github.com/teejayade2244/GitOps-Terraform-Iac-and-Kubernetes-manifests-Core-Serve-App.git
    targetRevision: master
    path: my-app
  destination:
    server: https://kubernetes.default.svc
    namespace: core-serve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true