apiVersion: v1
kind: Service
metadata:
  name: core-serve-frontend
  namespace: core-serve
spec:
  selector:
    app: core-serve-frontend
    type: front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
