apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  route:
    receiver: 'default-receiver'
    groupBy: ['alertname', 'cluster', 'service', 'severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    routes:
    # --- Monitoring namespace alerts ---
    - matchers:
      - name: namespace
        value: monitoring
        matchType: "="
      receiver: 'default-receiver'
      continue: true
      routes:
      - matchers:
        - name: severity
          value: critical
          matchType: "="
        receiver: 'critical-alerts'
        continue: true
        groupWait: 10s
        repeatInterval: 1h
      - matchers:
        - name: severity
          value: warning
          matchType: "="
        receiver: 'warning-alerts'
        continue: true
      - matchers:
        - name: team
          value: security
          matchType: "="
        receiver: 'security-alerts'
        continue: true
      - matchers:
        - name: service
          value: core-serve
          matchType: "="
        - name: severity
          value: critical
          matchType: "="
        receiver: 'core-serve-critical'
        groupBy: ['alertname', 'pod', 'instance']
        groupWait: 10s
        repeatInterval: 30m

    # --- Application namespace alerts ---
    - matchers:
      - name: namespace
        value: '(staging|production)'
        matchType: "=~"
      receiver: 'default-receiver'
      continue: true
      routes:
      - matchers:
        - name: severity
          value: critical
          matchType: "="
        receiver: 'critical-alerts'
        continue: true
        groupWait: 10s
        repeatInterval: 1h
      - matchers:
        - name: severity
          value: warning
          matchType: "="
        receiver: 'warning-alerts'
        continue: true
      - matchers:
        - name: team
          value: security
          matchType: "="
        receiver: 'security-alerts'
        continue: true
      - matchers:
        - name: service
          value: core-serve
          matchType: "="
        - name: severity
          value: critical
          matchType: "="
        receiver: 'core-serve-critical'
        groupBy: ['alertname', 'pod', 'instance']
        groupWait: 10s
        repeatInterval: 30m

    # --- Watchdog alerts ---
    - matchers:
      - name: alertname
        value: "Watchdog"
        matchType: "="
      receiver: 'null'
      continue: false

  # Inhibition rules
  inhibitRules:
  - sourceMatch:
    - name: severity
      value: 'critical'
      matchType: "="
    targetMatch:
    - name: severity
      value: 'warning'
      matchType: "="
    equal: ['alertname', 'cluster', 'service']

  receivers:
  - name: 'default-receiver'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      requireTLS: true
      tlsConfig:
        insecureSkipVerify: false
      html: |
        <h2>[ALERT] {{ .GroupLabels.alertname }}</h2>
        {{ range .Alerts }}
        <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
        <p><strong>Description:</strong> {{ .Annotations.description }}</p>
        <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
        <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
        <p><strong>Started:</strong> {{ .StartsAt }}</p>
        <hr>
        {{ end }}

  - name: 'critical-alerts'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      requireTLS: true
      tlsConfig:
        insecureSkipVerify: false
      html: |
        <h2>🚨 [CRITICAL] {{ .GroupLabels.alertname }}</h2>
        {{ range .Alerts }}
        <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
        <p><strong>Description:</strong> {{ .Annotations.description }}</p>
        <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
        <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
        <p><strong>Started:</strong> {{ .StartsAt }}</p>
        <hr>
        {{ end }}

  - name: 'warning-alerts'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      requireTLS: true
      tlsConfig:
        insecureSkipVerify: false
      html: |
        <h2>⚠️ [WARNING] {{ .GroupLabels.alertname }}</h2>
        {{ range .Alerts }}
        <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
        <p><strong>Description:</strong> {{ .Annotations.description }}</p>
        <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
        <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
        <p><strong>Started:</strong> {{ .StartsAt }}</p>
        <hr>
        {{ end }}

  - name: 'security-alerts'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      requireTLS: true
      tlsConfig:
        insecureSkipVerify: false
      html: |
        <h2>🔒 [SECURITY] {{ .GroupLabels.alertname }}</h2>
        {{ range .Alerts }}
        <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
        <p><strong>Description:</strong> {{ .Annotations.description }}</p>
        <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
        <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
        <p><strong>Started:</strong> {{ .StartsAt }}</p>
        <hr>
        {{ end }}

  - name: 'core-serve-critical'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      requireTLS: true
      tlsConfig:
        insecureSkipVerify: false
      html: |
        <h2>🚨 [CORE-SERVE CRITICAL] {{ .GroupLabels.alertname }}</h2>
        {{ range .Alerts }}
        <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
        <p><strong>Description:</strong> {{ .Annotations.description }}</p>
        <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
        <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
        <p><strong>Started:</strong> {{ .StartsAt }}</p>
        <hr>
        {{ end }}