# This is the complete Alertmanager configuration content.
# It will be base64-encoded and placed into the 'alertmanager.yaml' key
# within the specific Kubernetes Secret that your Alertmanager pod consumes.

global:
  # GLOBAL SMTP SETTINGS FOR GMAIL
  # These apply to ALL email_configs in ANY receiver.
  smtp_from: 'adebunmi33@gmail.com' # Your Gmail address
  smtp_smarthost: 'smtp.gmail.com:587' # Gmail's SMTP server and port
  smtp_auth_username: 'adebunmi33@gmail.com' # Your Gmail address for authentication
  smtp_auth_password: 'njid zanu qmtl fyjx' # Your Gmail App Password (no spaces, for direct secret encoding)
  smtp_require_tls: true # Essential for secure Gmail connection
  # If you want to remove other default global settings like pagerduty_url, etc., you can do so here.

route:
  receiver: 'default-receiver' # This receiver will be defined in the AlertmanagerConfig CRD
  group_by: ['alertname', 'cluster', 'service', 'severity'] # Global grouping
  group_wait: 30s # Wait 30 seconds for more alerts to join a new group
  group_interval: 5m # For existing groups, wait 5 minutes before sending new alerts
  repeat_interval: 4h # Re-send persistent alerts every 4 hours
  routes: [] # Specific routes will be defined in the AlertmanagerConfig CRD (next step)

receivers:
  - name: 'default-receiver'
    # This receiver primarily serves as a placeholder for the `route.receiver` above.
    # Its actual notification details will be defined in the AlertmanagerConfig CRD.
    # You can add a general Slack fallback here if desired:
    # slack_configs:
    #   - channel: '#alerts-general-fallback' # e.g., #alerts-fallback
    #     api_url: 'YOUR_SLACK_WEBHOOK_URL_GENERAL' # Replace with actual URL
    #     text: '{{ template "slack.default.message" . }}'

# --- TEMPLATE DEFINITIONS ---
# The content of your custom email template is embedded directly here.
templates:
  - name: 'email.tmpl' # This name is referenced in your AlertmanagerConfig CRD
    template: |
      {{ define "email.default.subject" -}}
      {{ .Status | toUpper }}: {{ .CommonLabels.alertname }} for {{ .CommonLabels.service }} ({{ .CommonLabels.severity | toUpper }})
      {{- end }}

      {{ define "email.default.html" -}}
      <!DOCTYPE html>
      <html>
      <head>
          <meta charset="UTF-8">
          <style>
              body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
              .container { max-width: 600px; margin: 0 auto; background-color: white; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
              .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center; }
              .header h1 { margin: 0; font-size: 24px; }
              .content { padding: 20px; }
              .alert-box { background-color: #fff3cd; border: 1px solid #ffeaa7; border-radius: 6px; padding: 15px; margin-bottom: 15px; }
              .alert-box.resolved { background-color: #d4edda; border-color: #c3e6cb; }
              .alert-info { display: grid; grid-template-columns: 120px 1fr; gap: 10px; margin-bottom: 10px; }
              .label { font-weight: bold; color: #495057; }
              .value { color: #212529; }
              .severity { padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; text-transform: uppercase; }
              .severity.critical { background-color: #dc3545; color: white; }
              .severity.warning { background-color: #ffc107; color: #212529; }
              .severity.info { background-color: #17a2b8; color: white; }
              .footer { background-color: #f8f9fa; padding: 15px 20px; border-radius: 0 0 8px 8px; font-size: 12px; color: #6c757d; text-align: center; }
              .timestamp { color: #6c757d; font-size: 14px; }
          </style>
      </head>
      <body>
          <div class="container">
              <div class="header">
                  <h1>🚨 Alert Notification</h1>
                  <p style="margin: 5px 0 0 0;">{{ .GroupLabels.alertname }}</p>
              </div>
              <div class="content">
                  {{ range .Alerts }}
                  <div class="alert-box{{ if eq .Status "resolved" }} resolved{{ end }}">
                      <div class="alert-info">
                          <div class="label">Status:</div>
                          <div class="value">{{ if eq .Status "resolved" }}✅ RESOLVED{{ else }}🔥 FIRING{{ end }}</div>
                          
                          <div class="label">Summary:</div>
                          <div class="value">{{ .Annotations.summary }}</div>
                          
                          <div class="label">Description:</div>
                          <div class="value">{{ .Annotations.description }}</div>
                          
                          <div class="label">Severity:</div>
                          <div class="value"><span class="severity {{ .Labels.severity }}">{{ .Labels.severity }}</span></div>
                          
                          {{ if .Labels.instance }}
                          <div class="label">Instance:</div>
                          <div class="value">{{ .Labels.instance }}</div>
                          {{ end }}
                          
                          {{ if .Labels.pod }}
                          <div class="label">Pod:</div>
                          <div class="value">{{ .Labels.pod }}</div>
                          {{ end }}
                          
                          {{ if .Labels.service }}
                          <div class="label">Service:</div>
                          <div class="value">{{ .Labels.service }}</div>
                          {{ end }}
                          
                          <div class="label">Started:</div>
                          <div class="value timestamp">{{ .StartsAt.Format "2006-01-02 15:04:05 MST" }}</div>
                          
                          {{ if .EndsAt }}
                          <div class="label">Ended:</div>
                          <div class="value timestamp">{{ .EndsAt.Format "2006-01-02 15:04:05 MST" }}</div>
                          {{ end }}
                      </div>
                  </div>
                  {{ end }}
              </div>
              <div class="footer">
                  <p>🔍 Prometheus Alertmanager | Cluster: {{ .GroupLabels.cluster | default "N/A" }} | Namespace: {{ .GroupLabels.namespace | default "N/A" }}</p>
              </div>
          </div>
      </body>
      </html>
      {{- end }}
