apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  route:
    receiver: 'default-receiver'
    groupBy: ['alertname', 'cluster', 'service', 'severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    routes:
    - matchers:
      - name: namespace
        value: monitoring 
      receiver: 'monitoring/main-rules-alert-config/default-receiver' 
      continue: true
      routes: 
      - matchers:
        - name: severity
          value: critical
        receiver: 'critical-alerts'
        continue: true
      - matchers:
        - name: severity
          value: warning
        receiver: 'warning-alerts'
        continue: true
      - matchers:
        - name: team
          value: security
        receiver: 'security-alerts'
        continue: true
      - matchers:
        - name: service
          value: core-serve 
        - name: severity
          value: critical
        receiver: 'core-serve-critical'
        groupBy: ['alertname', 'pod', 'instance']
        groupWait: 10s
        repeatInterval: 1h
    - matchers:
      - name: namespace
        value: 'staging|production'          
      receiver: 'monitoring/main-rules-alert-config/default-receiver' 
      continue: true
      routes:
      - matchers:
        - name: severity
          value: critical
        receiver: 'critical-alerts'
        continue: true
      - matchers:
        - name: severity
          value: warning
        receiver: 'warning-alerts'
        continue: true
      - matchers:
        - name: team
          value: security
        receiver: 'security-alerts'
        continue: true
      - matchers:
        - name: service
          value: core-serve
        - name: severity
          value: critical
        receiver: 'core-serve-critical'
        groupBy: ['alertname', 'pod', 'instance']
        groupWait: 10s
        repeatInterval: 1h
    - matchers:
      - name: alertname
        value: "Watchdog"
      receiver: 'null' 
      continue: false
  receivers:
  - name: 'default-receiver'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      requireTLS: true
      tlsConfig:
        insecureSkipVerify: false
      html: |
        <h2>[ALERT] {{ .GroupLabels.alertname }}</h2>
        {{ range .Alerts }}
        <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
        <p><strong>Description:</strong> {{ .Annotations.description }}</p>
        <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
        <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
        <p><strong>Started:</strong> {{ .StartsAt }}</p>
        <hr>
        {{ end }}

  - name: 'critical-alerts'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      requireTLS: true
      tlsConfig:
        insecureSkipVerify: false
      html: |
        <h2>🚨 [CRITICAL] {{ .GroupLabels.alertname }}</h2>
        {{ range .Alerts }}
        <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
        <p><strong>Description:</strong> {{ .Annotations.description }}</p>
        <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
        <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
        <p><strong>Started:</strong> {{ .StartsAt }}</p>
        <hr>
        {{ end }}

  - name: 'warning-alerts'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      requireTLS: true
      tlsConfig:
        insecureSkipVerify: false
      html: |
        <h2>⚠️ [WARNING] {{ .GroupLabels.alertname }}</h2>
        {{ range .Alerts }}
        <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
        <p><strong>Description:</strong> {{ .Annotations.description }}</p>
        <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
        <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
        <p><strong>Started:</strong> {{ .StartsAt }}</p>
        <hr>
        {{ end }}

  - name: 'security-alerts'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      requireTLS: true
      tlsConfig:
        insecureSkipVerify: false
      html: |
        <h2>🔒 [SECURITY] {{ .GroupLabels.alertname }}</h2>
        {{ range .Alerts }}
        <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
        <p><strong>Description:</strong> {{ .Annotations.description }}</p>
        <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
        <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
        <p><strong>Started:</strong> {{ .StartsAt }}</p>
        <hr>
        {{ end }}

  - name: 'core-serve-critical'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      requireTLS: true
      tlsConfig:
        insecureSkipVerify: false
      html: |
        <h2>🚨 [CORE-SERVE CRITICAL] {{ .GroupLabels.alertname }}</h2>
        {{ range .Alerts }}
        <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
        <p><strong>Description:</strong> {{ .Annotations.description }}</p>
        <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
        <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
        <p><strong>Started:</strong> {{ .StartsAt }}</p>
        <hr>
        {{ end }}