apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-main-config
  namespace: monitoring # Or whatever namespace your Alertmanager is in
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_hello: localhost
      smtp_require_tls: true
      smtp_tls_config:
        insecure_skip_verify: false
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_auth_username: 'adebunmi33@gmail.com'
      smtp_auth_password: 'njidzanuqmtlfyjx'
        name: smtp-secret
        key: password
      smtp_from: 'adebunmi33@gmail.com' # Global from address

    route:
      receiver: 'default-receiver'
      group_by: ['alertname', 'cluster', 'service', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
      - matchers:
        - severity: 'critical'
        receiver: 'critical-alerts'
        continue: true
      - matchers:
        - severity: 'warning'
        receiver: 'warning-alerts'
        continue: true
      - matchers:
        - team: 'security'
        receiver: 'security-alerts'
        continue: true
      - matchers:
        - service: 'core-serve'
        - severity: 'critical'
        receiver: 'core-serve-critical'
        group_by: ['alertname', 'pod', 'instance']
        group_wait: 10s
        repeat_interval: 1h

    receivers:
    - name: 'default-receiver'
      email_configs: # Use email_configs for native Alertmanager config
      - to: 'adebunmi33@gmail.com'
        send_resolved: true
        subject: '[ALERT] {{ .GroupLabels.alertname }}' # Native Alertmanager uses 'subject' directly
        html: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt }}
          {{ end }}

    - name: 'critical-alerts'
      email_configs:
      - to: 'adebunmi33@gmail.com'
        send_resolved: true
        subject: '🚨 [CRITICAL] {{ .GroupLabels.alertname }}'

    - name: 'warning-alerts'
      email_configs:
      - to: 'adebunmi33@gmail.com'
        send_resolved: true
        subject: '⚠️ [WARNING] {{ .GroupLabels.alertname }}'

    - name: 'security-alerts'
      email_configs:
      - to: 'adebunmi33@gmail.com'
        send_resolved: true
        subject: '🔒 [SECURITY] {{ .GroupLabels.alertname }}'

    - name: 'core-serve-critical'
      email_configs:
      - to: 'adebunmi33@gmail.com'
        send_resolved: true
        subject: '🚨 [CORE-SERVE CRITICAL] {{ .GroupLabels.alertname }}'