apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  route:
    receiver: 'default-receiver'
    groupBy: ['alertname', 'cluster', 'service', 'severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    routes:
    # Route for critical alerts
    - matchers:  # Fixed: changed from 'match' to 'matchers'
      - name: severity
        value: critical
      receiver: 'critical-alerts'
      continue: true

    # Route for warning alerts
    - matchers:
      - name: severity
        value: warning
      receiver: 'warning-alerts'
      continue: true

    # Route for security team-specific alerts
    - matchers:
      - name: team
        value: security
      receiver: 'security-alerts'
      continue: true

    # Route for critical alerts specific to 'core-serve' service
    - matchers:
      - name: service
        value: core-serve
      - name: severity
        value: critical
      receiver: 'core-serve-critical'
      groupBy: ['alertname', 'pod', 'instance']
      groupWait: 10s
      repeatInterval: 1h

  receivers:
  - name: 'default-receiver'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      subject: '[ALERT] {{ .GroupLabels.alertname }}'
      body: |
        {{ range .Alerts }}
        Alert: {{ .Annotations.summary }}
        Description: {{ .Annotations.description }}
        Severity: {{ .Labels.severity }}
        Instance: {{ .Labels.instance }}
        Started: {{ .StartsAt }}
        {{ end }}

  - name: 'critical-alerts'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      subject: '🚨 [CRITICAL] {{ .GroupLabels.alertname }}'

  - name: 'warning-alerts'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      subject: '⚠️ [WARNING] {{ .GroupLabels.alertname }}'

  - name: 'security-alerts'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      subject: '🔒 [SECURITY] {{ .GroupLabels.alertname }}'

  - name: 'core-serve-critical'
    emailConfigs:
    - to: 'adebunmi33@gmail.com'
      from: 'adebunmi33@gmail.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'adebunmi33@gmail.com'
      authPassword:
        name: smtp-secret
        key: password
      subject: '🚨 [CORE-SERVE CRITICAL] {{ .GroupLabels.alertname }}'