    # This is the main Alertmanager configuration, to be stored in a Kubernetes Secret.
    # It contains global SMTP settings and a base route.
    # AlertmanagerConfig CRD will merge with this.

    global:
      # Global SMTP settings for all email_configs in any receiver.
      # These are defined here because your AlertmanagerConfig v1alpha1 does not support them per receiver.
      smtp_from: 'adebunmi33@gmail.com' # Your Gmail address
      smtp_smarthost: 'smtp.gmail.com:587' # Gmail's SMTP server and port (You confirmed 465 works too, 587 is common for STARTTLS)
      smtp_auth_username: 'adebunmi33@gmail.com' # Your Gmail address for authentication
      smtp_auth_password: 'njid zanu qmtl fyjx' # Your Gmail App Password (NO SPACES HERE when you create the secret!)
      smtp_require_tls: true # Recommended for secure communication

    # Define a base route and default receiver here. AlertmanagerConfig will merge with this.
    route:
      receiver: 'default-receiver' # This receiver will be defined in the AlertmanagerConfig CRD
      group_by: ['alertname', 'cluster', 'service', 'severity'] # Global grouping
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes: [] # No specific routes here, they will come from AlertmanagerConfig

    receivers:
      # Define a minimal default receiver here. This ensures a base configuration is always present.
      # This receiver might only serve as a placeholder or send to a very general channel.
      # More specific receivers will be defined in the AlertmanagerConfig CRD.
      - name: 'default-receiver'
        # If you want a fallback Slack here, put it. Otherwise, this receiver just exists
        # to ensure Alertmanager doesn't complain about an undefined default receiver.
        # It's good practice to have at least one valid config here if it's the root receiver.
        # Example Slack config:
        # slack_configs:
        #   - channel: '#alerts-general-fallback'
        #     api_url: 'YOUR_SLACK_WEBHOOK_URL_GENERAL'
        #     text: '{{ template "slack.default.message" . }}'
    