apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
  labels:
    # This label MUST match the 'alertmanagerConfigSelector'
    # in your main Alertmanager CRD (e.g., kube-prometheus-stack-alertmanager).
    release: kube-prometheus-stack 
spec: 
  # The 'route' section here focuses only on routing rules to named receivers.
  # Global grouping parameters like `groupBy`, `groupWait`, etc. are defined in the main Alertmanager Secret (Part 1).
  route:
    receiver: 'default-receiver' # Must be a receiver defined in this CRD.

    routes:
    - matchers:
      - name: severity
        value: critical
      receiver: 'critical-alerts'
      continue: true 

    - matchers:
      - name: severity
        value: warning
      receiver: 'warning-alerts'
      continue: true

    - matchers:
      - name: team
        value: security
      receiver: 'security-alerts' 
      continue: true

    - matchers:
      - name: service
        value: core-serve
      - name: severity
        value: critical
      receiver: 'core-serve-critical' 
      # Per-route grouping overrides may or may not be fully supported in v1alpha1.
      # If this causes errors, remove these `groupBy`, `groupWait`, `repeatInterval` lines.
      groupBy: ['alertname', 'pod', 'instance'] 
      groupWait: 10s 
      repeatInterval: 1h 
      
  # The 'receivers' section defines the actual notification destinations.
  # Email configs here rely on the GLOBAL SMTP settings from the main Alertmanager Secret.
  # They now correctly reference the custom template functions.
  receivers:
  - name: 'default-receiver'
    emailConfigs:
      - to: 'adebunmi33@gmail.com' 
        sendResolved: true 
        html: true # This enables HTML emails
        # --- REFERENCING CUSTOM TEMPLATE FUNCTIONS ---
        subject: '{{ template "email.default.subject" . }}' # Subject from email.tmpl
        html_body: '{{ template "email.default.html" . }}' # HTML body from email.tmpl
        # --- END REFERENCING ---

  - name: 'critical-alerts'
    emailConfigs:
      - to: 'adebunmi33@gmail.com'
        sendResolved: true
        html: true
        subject: '{{ template "email.default.subject" . }}'
        html_body: '{{ template "email.default.html" . }}'
 
  - name: 'warning-alerts'
    emailConfigs:
      - to: 'adebunmi33@gmail.com'
        sendResolved: true
        html: true
        subject: '{{ template "email.default.subject" . }}'
        html_body: '{{ template "email.default.html" . }}'

  - name: 'security-alerts'
    emailConfigs:
      - to: 'adebunmi33@gmail.com'
        sendResolved: true
        html: true
        subject: '{{ template "email.default.subject" . }}'
        html_body: '{{ template "email.default.html" . }}'

  - name: 'core-serve-critical'
    emailConfigs:
      - to: 'adebunmi33@gmail.com'
        sendResolved: true
        html: true
        subject: '{{ template "email.default.subject" . }}'
        html_body: '{{ template "email.default.html" . }}'
