global:
  # GLOBAL SMTP SETTINGS FOR GMAIL
  # These apply to ALL email_configs in ANY receiver.
  smtp_from: 'adebunmi33@gmail.com' # Your Gmail address
  smtp_smarthost: 'smtp.gmail.com:587' # Gmail's SMTP server and port
  smtp_auth_username: 'adebunmi33@gmail.com' # Your Gmail address for authentication
  smtp_auth_password: 'njid zanu qmtl fyjx' # Your Gmail App Password (no spaces for the secret)
  smtp_require_tls: true # Essential for secure Gmail connection

# GLOBAL ROUTING DEFAULTS
# These parameters apply to ALL alerts that Alertmanager processes.
route:
  receiver: 'default-receiver' # This receiver will be defined in the AlertmanagerConfig CRD
  group_by: ['alertname', 'cluster', 'service', 'severity'] # Group alerts by these labels globally
  group_wait: 30s # Wait 30 seconds for more alerts to join a new group
  group_interval: 5m # For existing groups, wait 5 minutes before sending new alerts
  repeat_interval: 4h # Re-send persistent alerts every 4 hours
  routes: [] # Specific routes will be defined in the AlertmanagerConfig CRD
receivers:
  - name: 'default-receiver'
templates:
  - /etc/alertmanager/config/email.tmpl 
