# Save this as alertmanager-values.yaml
# Minimal values.yaml focused on Alertmanager configuration
alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'adebunmi33@gmail.com'
      smtp_auth_username: 'adebunmi33@gmail.com'
      smtp_auth_password_file: '/etc/alertmanager/secrets/smtp-secret/password'
      smtp_require_tls: true
    
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info' 
        equal:
          - 'namespace'
      - target_matchers:
          - 'alertname = InfoInhibitor'
    
    route:
      receiver: 'default-receiver'
      group_by: ['alertname', 'cluster', 'service', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
        - matchers:
            - 'alertname = Watchdog'
          receiver: 'null'
          
        - matchers:
            - 'severity = critical'
          receiver: 'critical-alerts'
          group_wait: 10s
          repeat_interval: 1h
          
        - matchers:
            - 'severity = warning'
          receiver: 'warning-alerts'
    
    receivers:
      - name: 'null'
        
      - name: 'default-receiver'
        email_configs:
          - to: 'adebunmi33@gmail.com'
            from: 'adebunmi33@gmail.com'
            subject: '[ALERT] {{ .GroupLabels.alertname }}'
            body: |
              {{ range .Alerts }}
              Alert: {{ .Annotations.summary }}
              Description: {{ .Annotations.description }}
              Severity: {{ .Labels.severity }}
              Started: {{ .StartsAt }}
              {{ end }}
            send_resolved: true
            
      - name: 'critical-alerts'
        email_configs:
          - to: 'adebunmi33@gmail.com'
            from: 'adebunmi33@gmail.com'
            subject: '🚨 [CRITICAL] {{ .GroupLabels.alertname }}'
            body: |
              {{ range .Alerts }}
              CRITICAL ALERT: {{ .Annotations.summary }}
              Description: {{ .Annotations.description }}
              Instance: {{ .Labels.instance }}
              Started: {{ .StartsAt }}
              {{ end }}
            send_resolved: true
            
      - name: 'warning-alerts'
        email_configs:
          - to: 'adebunmi33@gmail.com'
            from: 'adebunmi33@gmail.com'
            subject: '⚠️ [WARNING] {{ .GroupLabels.alertname }}'
            body: |
              {{ range .Alerts }}
              Warning: {{ .Annotations.summary }}
              Description: {{ .Annotations.description }}
              Started: {{ .StartsAt }}
              {{ end }}
            send_resolved: true

  alertmanagerSpec:
    secrets:
      - smtp-secret