apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: core-serve-staging-metrics
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: core-serve-backend-staging
  namespaceSelector:
    matchNames:
      - staging
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 14s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: core-serve-production-metrics
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: core-serve-backend-production
  namespaceSelector:
    matchNames:
      - production
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 14s
