# Base/Common values
app:
    type: back-end

container:
    resources:
        requests:
            memory: "240Mi"
            cpu: "250m"
        limits:
            memory: "1Gi"
            cpu: "500m"
    port: 5000

# Common probe settings
probes:
    liveness:
        path: /healthz
        initialDelay: 10
        period: 5
        timeout: 3
        failureThreshold: 3
    readiness:
        path: /readyz
        initialDelay: 5
        period: 3
        timeout: 2
        failureThreshold: 2

serviceAccount:
    name: core-serve-backend-sa

service:
    type: ClusterIP
    protocol: TCP
    port: 5000

topologySpread:
    maxSkew: 2
    zones:
        enabled: true
    nodes:
        enabled: true



